---
# python-pip installed during packages task on Fedora since epel doesn't exist
- name: Install python-pip on rpm based systems.
  yum:
    name: python-pip
    state: present
    enablerepo: epel
  when: ansible_pkg_mgr == "yum" and ansible_distribution != 'Fedora'

#- name: Install python-pip on apt based systems.
#  apt:
#    name: python-pip
#    state: present
#  when: ansible_pkg_mgr == "apt"

- name: Create the .pip directory for the teuthology user.
  file:
    path: "/home/{{ teuthology_user }}/.pip"
    owner: "{{ teuthology_user }}"
    group: "{{ teuthology_user }}"
    mode: 0644
    state: directory

- name: Create pip.conf and configure it to use our mirror
  template:
    src: pip.conf
    dest: "/home/{{ teuthology_user }}/.pip/pip.conf"
    owner: "{{ teuthology_user }}"
    group: "{{ teuthology_user }}"
    mode: 0644
