---
# Install and Configure a Kerberos client

- name: Install Kerberos Packages (RedHat)
  yum:
    name: krb5-workstation
    state: present
  when: ansible_os_family == 'RedHat'

# See http://tracker.ceph.com/issues/15439
- name: Clean apt cache
  command: apt-get clean
  when: ansible_os_family == 'Debian'

#- name: Update apt cache
#  apt:
#    update_cache: yes
  # Register and retry to work around transient http issues
# register: apt_cache_update
#  until: apt_cache_update|success
  # try for 2 minutes before failing
#  retries: 24
#  delay: 5
#  when: ansible_os_family == 'Debian'

#- name: Install Kerberos Packages (Debian)
#  apt:
#    name: krb5-user
#    state: present
#  when: ansible_os_family == 'Debian'

- name: Install Kerberos Packages (OpenSUSE Leap)
  zypper:
    name: krb5-client
    state: present
  when: ansible_os_family == 'Suse'

- name: Add krb5 config file
  template:
    src: 'krb5.conf'
    dest: '/etc/krb5.conf'
    owner: root
    group: root
    mode: 0644
