---

- name: Log the OS name, version and release
  debug: msg="Host {{ inventory_hostname }} is running {{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_distribution_release }})"

# loading major version specific vars
- name: Including major version specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yml"
    - empty.yml
  tags:
    - vars
    # We need these vars for the entitlements tag to work
    - entitlements

# configure things specific to yum systems
- include: yum_systems.yml
  when: ansible_pkg_mgr == "yum"

# configure things specific to apt systems
- include: apt_systems.yml
  when: ansible_pkg_mgr == "apt"

- include: zypper_systems.yml
  when: ansible_pkg_mgr == "zypper"

# configure Kerberos
- include: kerberos.yml
  tags:
    - kerberos

# upload custom disk monitoring scripts
- include: disk_monitoring.yml
  tags:
    - monitoring-scripts
#    - nagios

# configure nagios
- include: nagios.yml
  when: ansible_pkg_mgr != "zypper"
  tags:
    - nagios

- name: Get SELinux status
  command: getenforce
  register: selinux_status
  when: ansible_pkg_mgr == "yum"
  tags:
    - nagios

# configure selinux for nagios
- include: nrpe-selinux.yml
  when: ansible_os_family == "RedHat" and
        (selinux_status is defined and selinux_status.stdout != "Disabled")
  tags:
    - nagios
